[tool.poetry]
name = "pythonproject2"
version = "0.1.0"
description = ""
authors = ["TosLICK <anatosliy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
